var tabledataFiche = [
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
];


var tabledataClient = [
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
];
module.exports = { tabledataFiche, tabledataClient };


