var tabledataFiche = [
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "cloturé",
  },
  {
    code: "20574",
    client: "ABC Corporation",
    operateur: "Linda",
    matiere: "D2",
    durete: "62-64-HRC",
    designation: "Pièces de précision",
    qte: "90",
    poids: "12",
    prof: "-0.2",
    date: "28/12/2023",
    statut: "ouvert",
  },
  {
    code: "20575",
    client: "XYZ Tech",
    operateur: "Mike",
    matiere: "H13",
    durete: "48-50-HRC",
    designation: "Composants électroniques",
    qte: "120",
    poids: "15",
    prof: "-0.4",
    date: "30/12/2023",
    statut: "cloturé",
  },
  {
    code: "20576",
    client: "PQR Manufacturing",
    operateur: "Emily",
    matiere: "Aluminium",
    durete: "N/A",
    designation: "Structures légères",
    qte: "200",
    poids: "25",
    prof: "-0.5",
    date: "02/01/2024",
    statut: "ouvert",
  },
  {
    code: "20574",
    client: "ABC Industries",
    operateur: "Alex",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "75",
    poids: "18",
    prof: "-0.3",
    date: "03/01/2024",
    statut: "ouvert",
  },
  {
    code: "20575",
    client: "XYZ Manufacturing",
    operateur: "Sophie",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "100",
    poids: "22",
    prof: "-0.6",
    date: "05/01/2024",
    statut: "cloturé",
  },
  {
    code: "20576",
    client: "LMN Tech",
    operateur: "Daniel",
    matiere: "D2",
    durete: "62-64-HRC",
    designation: "Pièces de précision",
    qte: "50",
    poids: "14",
    prof: "-0.2",
    date: "08/01/2024",
    statut: "cloturé",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20574",
    client: "ABC Industries",
    operateur: "Alex",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "75",
    poids: "18",
    prof: "-0.3",
    date: "03/01/2024",
    statut: "ouvert",
  },
  {
    code: "20575",
    client: "XYZ Manufacturing",
    operateur: "Sophie",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "100",
    poids: "22",
    prof: "-0.6",
    date: "05/01/2024",
    statut: "ouvert",
  },
  {
    code: "20576",
    client: "LMN Tech",
    operateur: "Daniel",
    matiere: "D2",
    durete: "62-64-HRC",
    designation: "Pièces de précision",
    qte: "50",
    poids: "14",
    prof: "-0.2",
    date: "08/01/2024",
    statut: "cloturé",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20571",
    client: "3 MICRO",
    operateur: "Anwar",
    matiere: "E24",
    durete: "60-62-HRC",
    designation: "Pièces",
    qte: "125",
    poids: "15",
    prof: "-0.5",
    date: "20/12/2023",
    statut: "ouvert",
  },
  {
    code: "20572",
    client: "ABC Industries",
    operateur: "Sara",
    matiere: "A36",
    durete: "55-58-HRC",
    designation: "Assemblage",
    qte: "80",
    poids: "20",
    prof: "-0.3",
    date: "22/12/2023",
    statut: "cloturé",
  },
  {
    code: "20573",
    client: "XYZ Manufacturing",
    operateur: "John",
    matiere: "S45C",
    durete: "58-60-HRC",
    designation: "Composants",
    qte: "150",
    poids: "18",
    prof: "-0.7",
    date: "25/12/2023",
    statut: "ouvert",
  },
  {
    code: "20574",
    client: "ABC Corporation",
    operateur: "Linda",
    matiere: "D2",
    durete: "62-64-HRC",
    designation: "Pièces de précision",
    qte: "90",
    poids: "12",
    prof: "-0.2",
    date: "28/12/2023",
    statut: "ouvert",
  },
  {
    code: "20575",
    client: "XYZ Tech",
    operateur: "Mike",
    matiere: "H13",
    durete: "48-50-HRC",
    designation: "Composants électroniques",
    qte: "120",
    poids: "15",
    prof: "-0.4",
    date: "30/12/2023",
    statut: "ouvert",
  },
  {
    code: "20576",
    client: "PQR Manufacturing",
    operateur: "Emily",
    matiere: "Aluminium",
    durete: "N/A",
    designation: "Structures légères",
    qte: "200",
    poids: "25",
    prof: "-0.5",
    date: "02/01/2024",
    statut: "ouvert",
  },
];

var tabledataClient = [
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
  {
    raisonSociale: "3 MICRO",
    ville: "Casablanca",
    nomContact: "Sahid SMIHROU",
    Téléphone: "+212-653258475",
    option: "",
  },
  {
    raisonSociale: "ABC Corporation",
    ville: "Rabat",
    nomContact: "Fatima Ahmed",
    Téléphone: "+212-612345678",
    option: "",
  },
  {
    raisonSociale: "XYZ Solutions",
    ville: "Marrakech",
    nomContact: "Karim Soussi",
    Téléphone: "+212-665432189",
    option: "",
  },
];

var tabledataFour = [
  {
    nomFour: "Yamaha",
    poidsMax: "10",
    tempMax: "130",
    etatCharge: "cloturé",
    idcharge: "A123",
    dateTimeFin: "",
    numChargeProchain: "A124",
  },
  {
    nomFour: "Yamaha",
    poidsMax: "15",
    tempMax: "150",
    etatCharge: "ouvert",
    idcharge: "A321",
    dateTimeFin: "",
    numChargeProchain: "A322",
  },
  {
    nomFour: "Sony",
    poidsMax: "12",
    tempMax: "140",
    etatCharge: "ouvert",
    idcharge: "B456",
    dateTimeFin: "",
    numChargeProchain: "B457",
  },
  {
    nomFour: "LG",
    poidsMax: "20",
    tempMax: "160",
    etatCharge: "cloturé",
    idcharge: "C789",
    dateTimeFin: "",
    numChargeProchain: "C790",
  },
  {
    nomFour: "Samsung",
    poidsMax: "18",
    tempMax: "155",
    etatCharge: "ouvert",
    idcharge: "D654",
    dateTimeFin: "",
    numChargeProchain: "D655",
  },
  {
    nomFour: "Panasonic",
    poidsMax: "25",
    tempMax: "170",
    etatCharge: "cloturé",
    idcharge: "E987",
    dateTimeFin: "",
    numChargeProchain: "E988",
  },
  {
    nomFour: "Apple",
    poidsMax: "8",
    tempMax: "125",
    etatCharge: "ouvert",
    idcharge: "F321",
    dateTimeFin: "",
    numChargeProchain: "F322",
  },
  {
    nomFour: "HP",
    poidsMax: "22",
    tempMax: "165",
    etatCharge: "cloturé",
    idcharge: "G555",
    dateTimeFin: "",
    numChargeProchain: "G556",
  },
  {
    nomFour: "Dell",
    poidsMax: "14",
    tempMax: "145",
    etatCharge: "ouvert",
    idcharge: "H777",
    dateTimeFin: "",
    numChargeProchain: "H778",
  },
  {
    nomFour: "Lenovo",
    poidsMax: "16",
    tempMax: "155",
    etatCharge: "cloturé",
    idcharge: "I999",
    dateTimeFin: "",
    numChargeProchain: "I1000",
  },
];

var tabledataMesCharges = [
  
];

module.exports = { tabledataFiche, tabledataClient, tabledataFour };
